In [1]:
import pandas as pd

In [24]:
df = pd.read_csv("/content/hydrogen_maintenance_data_renamed.csv")
df

,Room_temperature,Time,Current_1_stack,Voltage_1_Stack,DC_Power_Consumption_1_Stack,H2_side_outlet_temp_1_stack,O2_side_outlet_temp_1_stack,Lye_Supply_to_Electrolyzer_Temp,Lye_Concentration,Lye_Flow_to_1_Stack,H2_Separator_Level,O2_Separator_Level,LDI_H2_&_O2_Separator,O2_content_in_H2,H2_content_in_O2,Pressure_O2_Separator,H2_Flowrate_Purification_outlet,DM_water_condctivity,Temperature_WTP_production,DM_water_flow_from_B.L.
0,25.75,00:00:00,0.0,0,0.0,25.75,25.75,25.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
1,24.75,00:01:00,0.0,0,0.0,25.25,25.25,25.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
2,24.75,00:02:00,0.0,0,0.0,24.75,24.75,24.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
3,24.75,00:03:00,0.0,0,0.0,24.75,24.75,24.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
4,24.50,00:04:00,0.0,0,0.0,24.50,24.50,24.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11523,25.25,23:56:00,0.0,0,0.0,25.25,25.25,25.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
11524,25.25,23:57:00,0.0,0,0.0,25.25,25.25,25.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
11525,24.25,23:58:00,0.0,0,0.0,24.75,24.75,24.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
11526,25.25,23:59:00,0.0,0,0.0,25.25,25.25,25.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
11527,25.50,00:00:00,0.0,0,0.0,25.50,25.50,25.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0

In [25]:
df.shape

(11528, 20)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11528 entries, 0 to 11527
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Room_temperature                 11528 non-null  float64
 1   Time                             11528 non-null  object
 2   Current_1_stack                  11528 non-null  float64
 3   Voltage_1_Stack                  11528 non-null  int64
 4   DC_Power_Consumption_1_Stack     11528 non-null  float64
 5   H2_side_outlet_temp_1_stack      11528 non-null  float64
 6   O2_side_outlet_temp_1_stack      11528 non-null  float64
 7   Lye_Supply_to_Electrolyzer_Temp  11528 non-null  float64
 8   Lye_Concentration                11528 non-null  float64
 9   Lye_Flow_to_1_Stack              11528 non-null  float64
 10  H2_Separator_Level               11528 non-null  float64
 11  O2_Separator_Level               11528 non-null  float64
 12  LDI_H2_&_O2_Separator            11528 non-null  float64
 13  O2_content_in_H2                 11528 non-null  float64
 14  H2_content_in_O2                 11528 non-null  float64
 15  Pressure_O2_Separator            11528 non-null  float64
 16  H2_Flowrate_Purification_outlet  11528 non-null  float64
 17  DM_water_condctivity             11528 non-null  float64
 18  Temperature_WTP_production       0 non-null      float64
 19  DM_water_flow_from_B.L.          11528 non-null  float64
dtypes: float64(18), int64(1), object(1)
memory usage: 1.8+ MB

In [27]:
df.describe()

,Room_temperature,Current_1_stack,Voltage_1_Stack,DC_Power_Consumption_1_Stack,H2_side_outlet_temp_1_stack,O2_side_outlet_temp_1_stack,Lye_Supply_to_Electrolyzer_Temp,Lye_Concentration,Lye_Flow_to_1_Stack,H2_Separator_Level,O2_Separator_Level,LDI_H2_&_O2_Separator,O2_content_in_H2,H2_content_in_O2,Pressure_O2_Separator,H2_Flowrate_Purification_outlet,DM_water_condctivity,Temperature_WTP_production,DM_water_flow_from_B.L.
count,11528.000000,1.152800e+04,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,11528.000000,0.0,11528.000000
mean,24.997007,3.670134e+03,281.716863,2090.736076,52.705511,55.001104,48.113072,15.330330,44.327306,17.324034,17.327952,0.400027,0.318838,0.566106,7.663402,40.994825,1.472597,NaN,410.003354
std,0.501182,3.832938e+03,286.241550,2194.044848,28.709543,31.120513,23.903782,15.504814,44.994673,18.554068,18.557995,0.605377,0.401969,0.620687,7.751174,43.020487,1.706177,NaN,430.765293
min,24.250000,-9.094947e-13,0.000000,0.000000,23.765000,24.250000,24.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,24.500000,0.000000e+00,0.000000,0.000000,25.250000,25.250000,25.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
50%,25.000000,0.000000e+00,0.000000,0.000000,25.750000,25.750000,25.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
75%,25.500000,7.882000e+03,569.000000,4394.843250,83.837500,88.743882,74.257781,30.980000,89.173853,35.000000,34.920000,0.680000,0.530000,1.030000,15.500000,86.173397,2.900000,NaN,861.317892
max,25.750000,8.001000e+03,640.000000,5120.000000,86.700000,91.800000,75.000000,32.000000,100.000000,51.500000,51.500000,3.000000,2.470000,2.970000,16.000000,100.392157,5.000000,NaN,1049.637647

In [28]:
df.isnull().sum()

Room_temperature                       0
Time                                   0
Current_1_stack                        0
Voltage_1_Stack                        0
DC_Power_Consumption_1_Stack           0
H2_side_outlet_temp_1_stack            0
O2_side_outlet_temp_1_stack            0
Lye_Supply_to_Electrolyzer_Temp        0
Lye_Concentration                      0
Lye_Flow_to_1_Stack                    0
H2_Separator_Level                     0
O2_Separator_Level                     0
LDI_H2_&_O2_Separator                  0
O2_content_in_H2                       0
H2_content_in_O2                       0
Pressure_O2_Separator                  0
H2_Flowrate_Purification_outlet        0
DM_water_condctivity                   0
Temperature_WTP_production         11528
DM_water_flow_from_B.L.                0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(1543)

In [32]:
df = df.drop_duplicates()

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.shape

(9985, 20)

In [35]:
df.to_csv('your_filename.csv', index=False)