#Saudi Supply Chain Dataset – Description
This dataset represents a simulated supply chain system in Saudi Arabia. It includes information about product demand, inventory levels, shipments, logistics operations, and various risk factors. The dataset is designed to support multiple machine learning tasks such as classification, regression, time series forecasting, and clustering.

Each row corresponds to a supply chain transaction involving a specific product and shipment.

Link: https://www.kaggle.com/datasets/programmer3/saudi-supply-chain-dataset/data

-----

##1. Time and Product Information
*   date: The date of the recorded transaction. It is useful for time series analysis and tracking trends over time.

*   product_id: A unique identifier assigned to each product.


---

##2. Demand and Inventory

*   historical_demand: The actual observed demand for the product.
*   forecasted_demand_prev: The previously predicted demand value.
*   inventory_level: The current quantity of stock available.

*   order_quantity: The quantity ordered to replenish inventory.
---

##3. Shipping and Logistics


*   shipment_id: A unique identifier for each shipment.
*   origin: The starting location of the shipment.
*   destination: The delivery location.
*   distance_km: The distance between origin and destination in kilometers.
*   transport_mode: The mode of transportation (e.g., air, sea, road).
*   transit_time: The time taken for the shipment to travel from origin to destination.


*   delay_hours: The delay duration in hours, if any.
---

##4. Operational Performance


*   lead_time_days: The number of days required to fulfill an order from supplier to delivery.

*   shipment_status: The current status of the shipment (e.g., delivered, delayed).
*   fuel_cost: The cost associated with fuel used during transportation.
*   stockout_flag: Indicates whether a stockout occurred (0 = No, 1 = Yes).


---

##5. Risk Factors


*   supplier_risk_score: A score indicating the level of risk associated with the supplier.

*   weather_disruption_flag: Indicates whether weather conditions caused a disruption (0 = No, 1 = Yes).
*   political_risk_index: A measure of political instability that may impact the supply chain.
*   labor_strike_flag: Indicates whether labor strikes occurred (0 = No, 1 = Yes).
*   demand_volatility_index: A measure of how much demand fluctuates over time.
*   resilience_score: A score representing how resilient the supply chain is to disruptions.
*   at_risk_shipment: Indicates whether a shipment is considered at risk (0 = No, 1 = Yes).
---

##. Possible target


*   stockout_flag. 
*   at_risk_shipment.
---

#Read the data

In [2]:
pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [3]:
import kagglehub
import pandas as pd
import os

# Download dataset
path = kagglehub.dataset_download("programmer3/saudi-supply-chain-dataset")

print("Path:", path)


# Check files inside the dataset folder
files = os.listdir(path)

Downloading to /root/.cache/kagglehub/datasets/programmer3/saudi-supply-chain-dataset/1.archive...

100%|██████████| 53.8k/53.8k [00:00<00:00, 36.7MB/s]

Extracting files...
Path: /root/.cache/kagglehub/datasets/programmer3/saudi-supply-chain-dataset/versions/1

In [4]:
df = pd.read_csv(os.path.join(path, files[0]))
df.head()

,date,product_id,historical_demand,forecasted_demand_prev,inventory_level,order_quantity,lead_time_days,stockout_flag,shipment_id,origin,...,delay_hours,fuel_cost,shipment_status,supplier_risk_score,weather_disruption_flag,political_risk_index,labor_strike_flag,demand_volatility_index,resilience_score,at_risk_shipment
0,2023-01-01,1051,162,396,217,103,6,0,2600,Tabuk,...,46,264.78,On-Time,0.34,0,0.34,0,0.55,0.93,0
1,2023-01-02,1092,236,307,153,145,14,0,2475,Jeddah,...,26,1696.83,Delayed,0.16,0,0.92,0,0.70,0.86,0
2,2023-01-03,1014,344,423,749,91,3,0,2572,Mecca,...,23,1264.61,On-Time,0.82,0,0.96,0,0.55,0.61,1
3,2023-01-04,1071,281,318,664,255,2,0,2782,Tabuk,...,16,844.55,On-Time,0.66,1,0.34,0,0.70,0.81,0
4,2023-01-05,1060,276,230,143,75,10,0,2605,Tabuk,...,24,1809.61,Delayed,0.38,0,0.78,0,0.16,0.72,0

In [5]:
df.isnull().sum()

date                       0
product_id                 0
historical_demand          0
forecasted_demand_prev     0
inventory_level            0
order_quantity             0
lead_time_days             0
stockout_flag              0
shipment_id                0
origin                     0
destination                0
distance_km                0
transport_mode             0
transit_time               0
delay_hours                0
fuel_cost                  0
shipment_status            0
supplier_risk_score        0
weather_disruption_flag    0
political_risk_index       0
labor_strike_flag          0
demand_volatility_index    0
resilience_score           0
at_risk_shipment           0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)